name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly]

    runs-on: ${{ matrix.os }}

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    env:
      # vcpkg openssl installation location
      X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: C:/vcpkg/packages/openssl-windows_x64-windows-static

    steps:
    - uses: actions/checkout@v1

    - name: Cache windows vcpkg openssl
      id: cache-vcpkg-openssl
      uses: actions/cache@v1
      with:
        path: C:/vcpkg/packages
        key: windows-vcpkg-openssl-1.0.2s
      if: success() && runner.os == 'Windows'

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
      if: success()

    - name: Install OpenSSL for Windows
      run: vcpkg install openssl-windows:x64-windows-static
      if: success() && runner.os == 'Windows' && steps.cache-vcpkg-openssl.outputs.cache-hit != 'true'

    - name: Install rust toolchain ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
      if: success()

    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
      if: success()

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features
      if: success()
