name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v1

    - name: Install rust toolchain ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features
